### ISSUE TITLE
Bug: png.hexpat "No variable named 'chunk' found"

### ISSUE THREAD

**Issue by igoforth** [WerWolv/ImHex-Patterns#143]
Problem:

```text
E: error[E0003]: Variable error.
E:   --> <Source Code>:176:18
E: 176 |     return chunk.name;
E:                        ^
E:                        No variable named 'chunk' found.
E: 
E: 
I: Evaluation took 0.0021474s
```

Source (line 173):

```c
} [[name(chunkValueName(this))]];

fn chunkValueName(ref chunk_t chunk) {
    return chunk.name;
};
```

Proposed fix (line 173):

```c
} [[name(this.name)]];
```

**Comment by gmestanley** [comment]
On the latest nightly (version 1.30.1) it works fine, are you using the base version or an older one?

**Comment by turtleisaac** [comment]
Same issue for me. The about page says "Version 1.30 (1.30.1)"

**Comment by paxcut** [comment]
A couple of things I think I should mention.
1) Without a specific input file that gives the error we can only guess and the png files I tested all ran fine without errors.
2) even if your version number is the latest, you are probably running a release version which, compared to a nightly build found at the bottom of https://imhex.werwolv.net/ is old and lacks many bug fixes. so you may be running into a bug thats already fixed.

**Comment by igoforth** [comment]
@paxcut 

It doesn't make sense to include an input file because the error is a syntax error.

**Comment by paxcut** [comment]
The error is reported as a syntax error because the interpreter  is unable to find a variable that should be available. That variable is the argument to the function being passed as a reference. If the file that you use never calls that function the error won't be seen. Sp it would make sense to provide an input that uses the function and forces the error to occur.

There was a bug about passing references in that was fixed after the last release. Before the fix functions would fail to see the arguments being passed as references which is exactly what you describe. That bug was fixed and now functions have no problems using reference arguments . Your fix only avoids the issue by not using a function at all so it wouldn't actually fix the problem and just get around it.

Try downloading a nightly and running your tests to confirm or deny my assumptions.

**Comment by igoforth** [comment]
@paxcut 

I haven't yet tested the nightly, but I tested again on Windows 1.30.1. I still get the error. No file is required to be open to get the error.

![image](https://github.com/WerWolv/ImHex-Patterns/assets/20114381/2401620f-35c5-4fd7-b8d3-3eba6c6d778a)

```c
#pragma MIME image/png
#pragma endian big

#include <std/mem.pat>

struct header_t {
    u8 highBitByte;
    char signature[3];
    char dosLineEnding[2];
    char dosEOF;
    char unixLineEnding;
};

struct actl_t {
    u32 frames [[comment("Total № of frames in animation")]];
    u32 plays [[comment("№ of times animation will loop")]];
} [[comment("Animation control chunk"), name("acTL")]];

enum ColorType: u8 {
    Grayscale = 0x0,
    RGBTriple = 0x2,
    Palette,
    GrayscaleAlpha,
    RGBA = 0x6
};

enum Interlacing: u8 {
    None,
    Adam7
};

struct ihdr_t {
    u32 width [[comment("Image width")]];
    u32 height [[comment("Image height")]];
    u8 bit_depth;
    ColorType color_type [[comment("PNG Image Type")]];
    u8 compression_method [[comment("Only 0x0 = zlib supported by most")]];
    u8 filter_method [[comment("Only 0x0 = adaptive supported by most")]];
    Interlacing interlacing;
};

enum sRGB: u8 {
    Perceptual = 0x0,
    RelativeColorimetric,
    Saturation,
    AbsoluteColorimetric
};

enum Unit: u8 {
    Unknown,
    Meter
};

struct phys_t {
    u32 ppu_x [[comment("Pixels per unit, X axis")]];
    u32 ppu_y [[comment("Pixels per unit, Y axis")]];
    Unit unit;
};

enum BlendOp: u8 {
    Source = 0x0,
    Over
};

enum DisposeOp: u8 {
    None = 0x0,
    Background,
    Previous
};

struct fctl_t {
    u32 sequence_no [[comment("Sequence №")]];
    u32 width [[comment("Frame width")]];
    u32 height;
    u32 xoff;
    u32 yoff;
    u16 delay_num;
    u16 delay_den;
    DisposeOp dispose_op;
    BlendOp blend_op;
};

struct fdat_t {
    u32 sequence_no;
};

fn text_len() {
   u64 len = parent.parent.length - ($ - addressof(parent.keyword));
   return len;
};

struct itxt_t {
    char keyword[];
    u8 compression_flag;
    u8 compression_method;
    char language_tag[];
    char translated_keyword[];
    char text[text_len()];
};

struct ztxt_t {
    char keyword[];
    u8 compression_method;
    char text[text_len()];
};

struct text_t {
    char keyword[];
    char text[text_len()];
};

struct iccp_t {
    char keyword[];
    u8 compression_method;
    u8 compressed_profile[text_len()];
};

struct palette_entry_t {
    u24 color;
} [[inline]];

struct chunk_t {
    u32 length [[color("17BECF")]];
    char name[4];

    #define IHDR_k "IHDR"
    #define PLTE_k "PLTE"
    #define sRGB_k "sRGB"
    #define pHYs_k "pHYs"
    #define iTXt_k "iTXt"
    #define tEXt_k "tEXt"
    #define zTXt_k "zTXt"
    #define IDAT_k "IDAT"
    #define IEND_k "IEND"
    #define gAMA_k "gAMA"
    #define iCCP_k "iCCP"
    #define acTL_k "acTL"
    #define fdAT_k "fdAT"
    #define fcTL_k "fcTL"

    if (name == IHDR_k) {
        ihdr_t ihdr [[comment("Image Header chunk"), name("IHDR")]];
    } else if (name == PLTE_k) {
        palette_entry_t entries[length / 3];
    } else if (name == sRGB_k) {
        sRGB srgb;
    } else if (name == pHYs_k) {
        phys_t phys;
    } else if (name == acTL_k) {
        actl_t  actl [[comment("Animation control chunk")]];
    } else if (name == fcTL_k) {
        fctl_t fctl [[comment("Frame control chunk")]];
    } else if (name == iTXt_k) {
        itxt_t text;
    } else if (name == gAMA_k) {
    	u32 gamma [[name("image gamma"), comment("4 byte unsigned integer representing gamma times 100000")]];
    } else if (name == iCCP_k) {
    	iccp_t iccp;
    } else if (name == tEXt_k) {
        text_t text;
    } else if (name == zTXt_k) {
        ztxt_t text;
    } else if (name == iCCP_k) {
        iccp_t iccp;
    } else if (name == fdAT_k) {
        fdat_t fdat [[comment("Frame data chunk")]];
        u8 data[length-sizeof(u32)];
    } else {
        u8 data[length];
    }

    u32 crc;
} [[name(chunkValueName(this))]];

fn chunkValueName(ref chunk_t chunk) {
    return chunk.name;
};

struct chunk_set {
    chunk_t chunks[while(builtin::std::mem::read_string($ + 4, 4) != "IEND")] [[inline]];
} [[inline]];

struct Chunks {
    chunk_t ihdr_chunk [[comment("PNG Header chunk")]];
    chunk_set set [[comment("PNG Chunks"), name("Chunks"), inline]];
    chunk_t iend_chunk [[comment("Image End Chunk")]];
};

u8 visualizer[std::mem::size()] @ 0x00 [[sealed, hex::visualize("image", this)]];
header_t header @ 0x00 [[comment("PNG file signature"), name("Signature")]];
Chunks chunks @ 0x08 [[name("Chunks")]];
```

**Comment by paxcut** [comment]
you are using MTUSize.png if you make that available I could test it for you.

**Comment by igoforth** [comment]
I made some edits to my previous comment, thanks :)

**Comment by paxcut** [comment]
I am afraid that link is not working.  Use Preview to check the link as there are problems posting links. the easiest way is to drag the file. for example try this one which works for me
![png hexpat](https://github.com/WerWolv/ImHex-Patterns/assets/53811119/75f57b60-3fb6-49eb-bbef-99befa9b5c8e)

**Comment by igoforth** [comment]
> I am afraid that link is not working. Use Preview to check the link as there are problems posting links. the easiest way is to drag the file. for example try this one which works for me ![png hexpat](https://user-images.githubusercontent.com/53811119/256941813-75f57b60-3fb6-49eb-bbef-99befa9b5c8e.png)

My bad, seems like I have to embed it. Try the below.

![MTUSize](https://github.com/WerWolv/ImHex-Patterns/assets/20114381/907b8579-c042-468a-b143-dd0869861f5f)

**Comment by paxcut** [comment]
Actually the link worked nut i thought i was being spammed because of the choice for the picture. I apologize for suggesting otherwise.

**Comment by paxcut** [comment]
it worked ok here so i think the bug was fixed already
![image](https://github.com/WerWolv/ImHex-Patterns/assets/53811119/c6b7748e-56d2-4783-a896-eeb2310a313b)

**Comment by paxcut** [comment]
if you can't/don't want to download a nightly you can also test patterns online at https://pl.werwolv.net/ that should always run latest commit available. If the issue is resolved please close it.
